# ============================
# APPLICATION
# ============================
spring.application.name=Rumora_demo
server.port=${PORT:8080}

# ============================
# DATABASE (PostgreSQL)
# ============================
# ?????????? ?????????? ?????, ?? ?????? ???????? ?? ????????? ??? ????????? ??????????
SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d4uq8ffpm1nc73bb53s0-a.oregon-postgres.render.com:5432/rumora_db
spring.datasource.username=rumora_user
spring.datasource.password=WSYWV7YZGiZ7KZUDE8TC1C1hkPDKenpp

#spring.datasource.url=jdbc:postgresql://localhost:5432/database_setup
#spring.datasource.username=postgres
#spring.datasource.password=dkd0066460

spring.datasource.driver-class-name=org.postgresql.Driver

# ============================
# JPA / HIBERNATE
# ============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# ============================
# DATA INITIALIZATION
# ============================
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# ============================
# FILE UPLOAD
# ============================
upload.dir=uploads

# ???? ??? ??????????? ????????: ??????? ? ????? ????? ???????? ?? /uploads/...
spring.web.resources.static-locations=classpath:/static/,file:${upload.dir}/

# ???????????? ?????? ???????? (500 ?? ? ??? ? ????)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ============================
# SECURITY / JWT
# ============================
jwt.secret=${JWT_SECRET:I4fl9s0xhq3D9Bkmg37cQjzSV4WSxv87CFDSxI/CAbdGtTd6GcSIFDDqYfUQl7r0mdINXg/VPqfVoruZlTpt8g==}
jwt.expiration=${JWT_EXPIRATION:604800000}

# ============================
# DOCKER COMPOSE (?????????)
# ============================
spring.docker.compose.enabled=false